<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function drutube_misc_ctools_plugin_directory($module, $plugin) {
  if ($module == 'vud') {
    return $plugin;
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function drutube_misc_field_formatter_info() {
  return array(
    'drutube_misc_taxonomy_term_reference_link' => array(
      'label' => t('Drutube: Link to a Search View'),
      'field types' => array('taxonomy_term_reference'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function drutube_misc_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  // Terms whose tid is 'autocreate' do not exist
  // yet and $item['taxonomy_term'] is not set. Theme such terms as
  // just their name.

  switch ($display['type']) {
    case 'drutube_misc_taxonomy_term_reference_link':
      $delta = 0;
      foreach ($items as $item) {
        if ($item['tid'] == 'autocreate') {
          $element[$delta] = array(
            '#markup' => check_plain($item['name']),
          );
          $delta++;
        } else {
           $tids[] = $item['tid'];
        }
      }
      if(empty($tids)) {
        return $element;
      }
      $terms = taxonomy_term_load_multiple($tids);
      foreach ($terms as $term) {
        $element[$delta] = array(
            '#type' => 'link',
            '#title' => $term->name,
            '#href' => 'video',
            '#options' => array('query' => array('f[0]' => 'field_term_topics:'.$term->tid)),
          );
        $delta++;
      }
  }
  return $element;
}
